services:
  - type: web
    name: pjsofonic-crm-frontend
    env: static
    buildCommand: "npm run build"
    staticPublishPath: "./dist"
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://pjsofonic-crm-backend.onrender.com/api/v1"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
